- id: '1590852572769'
  alias: Balcony lights on sunset
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition:
  - above: 15
    below: 50
    condition: device
    device_id: e9a9d49ad37440dfa36b67a61e3766df
    domain: sensor
    entity_id: sensor.aqara_balcon_temperature
    type: is_temperature
  action:
  - device_id: 7069061b257e420a946db3cebd51895c
    domain: switch
    entity_id: switch.40505046c44f33b6dba4_1
    type: turn_on
- id: '1590853235952'
  alias: A dormir
  description: Apagar la luz del balcon, tele, receiver y deco
  trigger:
  - device_id: 2598719517a24dec8c6f2c740a09e04a
    domain: hue
    platform: device
    subtype: dim_down
    type: remote_button_long_release
  condition: []
  action:
  - device_id: 7069061b257e420a946db3cebd51895c
    domain: switch
    entity_id: switch.40505046c44f33b6dba4_1
    type: turn_off
  - data:
      command: PowerOff
      device: 69420543
    entity_id: remote.harmony_hub
    service: remote.send_command
  - data:
      command: PowerOff
      device: 69420668
    entity_id: remote.harmony_hub
    service: remote.send_command
  - data:
      command: PowerOff
      device: 69420586
    entity_id: remote.harmony_hub
    service: remote.send_command
- id: '1591168409931'
  alias: Update OpenUV every 30 minutes during the daytime
  description: ''
  trigger:
  - minutes: '30'
    platform: time_pattern
  condition:
  - condition: and
    conditions:
    - after: sunrise
      before: sunset
      condition: sun
  action:
  - data: {}
    service: openuv.update_data
