
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# http:
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

frontend:
  themes: !include_dir_merge_named themes

webostv:
  host: 192.168.1.207
  name: LG OLED Living
  turn_on_action:
    service: persistent_notification.create
    data:
      message: "Turn on action"
  customize:
    sources:
      - Apple TV
      - Home Theatre
      - Live TV
      - Sky

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_token
    allowed_chat_ids:
      - 8653176
      - 35636505

notify:
  - name: emiliano
    platform: telegram
    chat_id: 8653176
  - name: vicky
    platform: telegram
    chat_id: 35636505
  - name: telegram_bot
    platform: group
    services:
      - service: emiliano
      - service: vicky 

hue:
  bridges:
    - host: 192.168.1.206
      allow_unreachable: true
      allow_hue_groups: true

light:
  - platform: group
    name: Comedor Lights
    entities:
      - light.comedor_color
      - light.comedor_filament
  - platform: group
    name: Living Lights
    entities:
      - light.spot_1
      - light.spot_2
      - light.spot_3
      - light.kallax
  - platform: group
    name: Pasillo Lights
    entities:
      - light.pasillo_1
      - light.pasillo_2
  - platform: group
    name: Bedroom Lights
    entities:
      - light.habitacion_1
      - light.habitacion_2
  - platform: group
    name: Ofi Lights
    entities:
      - light.ofi_1
      - light.ofi_2

media_extractor:

influxdb: !include influxdb.yaml

recorder:

media_player:
  - platform: onkyo
    host: 192.168.1.200
    name: onkyo
    max_volume: 70
    sources:
      tv: "TV"
      phono: "Vinilos"
      network,net: "Network"

camera:
  - platform: generic
    name: meteogram
    still_image_url: https://www.yr.no/place/Germany/Berlin/Berlin/meteogram.svg
    content_type: 'image/svg+xml'

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: disk_use_percent
        arg: /mnt/timecapsule2
      - type: memory_use_percent
      - type: memory_free
      - type: load_15m
      - type: last_boot
  - platform: aftership
    api_key: !secret aftership_api_key
  - platform: climacell    
    api_key: !secret climacell_api_key
    name: climacell
    units: metric
    timelines:
      - name: "" #Realtime
        timestep: "1m"
        forecast_observations: 1
        fields:
          - temperature
          - temperatureApparent
          - humidity
          - windSpeed
          - windDirection
          - windgust
          - pressure
          - precipicationIntensity
          - precipitationType
          - visibility
          - cloudCover
          - weather_condition
          - pollen_tree
          - pollen_weed
          - pollen_grass
          - co
          - epa_aqi
          - epa_health_concern
          - no2
          - o3
          - pm10
          - pm25
          - so2
        update: auto
        scan_interval:
          # At least one of these must be specified:
          days: 0
          hours: 0
          minutes: 31
          seconds: 0
          milliseconds: 0
      - name: "" #daily
        forecast_observations: 5
        fields:
          - temperature
          - temperatureMin
          - temperatureMax
          - precipitationIntensityMin
          - precipitationIntensityMax
          - precipitation_probability
          - weather_condition
        scan_interval:
          # At least one of these must be specified:
          days: 0
          hours: 3
          minutes: 0
          seconds: 0
          milliseconds: 0
        exclude_interval:
          1:
            - "10:00"
            - "12:00"
          2:
            - "00:00"
            - "06:30"
google:
  client_id: 555731529003-9p80ho5139m26gm83n4bu219m1c5ug02.apps.googleusercontent.com
  client_secret: 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
  #client_id: !secret google_client_id
  #client_secret: !secret google_client_secret

