
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

hue:
  bridges:
    - host: 10.0.0.20
      allow_unreachable: true
      allow_hue_groups: true

light:
  - platform: group
    name: Comedor Lights
    entities:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2
  - platform: group
    name: Living Lights
    entities:
      - light.hue_color_spot_1
      - light.hue_color_spot_2
      - light.hue_color_spot_3
  - platform: group
    name: Pasillo Lights
    entities:
      - light.hue_white_lamp_1
      - light.hue_white_lamp_2

media_extractor:

influxdb: !include influxdb.yaml

openuv:
  api_key: !secret openuv_api_key

recorder:

camera:
  - platform: generic
    name: meteogram
    still_image_url: https://www.yr.no/place/Germany/Berlin/Berlin/meteogram.svg
    content_type: 'image/svg+xml'

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: disk_use_percent
        arg: /mnt/timecapsule2
      - type: memory_use_percent
      - type: memory_free
      - type: load_15m
      - type: last_boot
  - platform: aftership
    api_key: !secret aftership_api_key
  - platform: climacell
    api_key: !secret climacell_api_key
    name: climacell
    monitored_conditions:
      realtime:
        - weather_condition
        - temperature
        - feels_like
        - humidity
        - visibility
        - cloud_cover
        - precipitation
        - precipitation_type
        - pressure
        - wind_speed
        - wind_direction
        - wind_gust
        - moon_phase
        - sunset
        - sunrise
        - pollen_tree
        - pollen_weed
        - pollen_grass
        - co
        - epa_aqi
        - epa_health_concern
        - no2
        - o3
        - pm10
        - pm25
        - so2
      forecast:
        - weather_condition
        - temperature
        - precipitation
        - precipitation_probability
    scan_interval:
      # At least one of these must be specified:
      days: 0
      hours: 0
      minutes: 31
      seconds: 0
      milliseconds: 0

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

